name: counter
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: 4.0.0-dev.4
  isar_flutter_libs: 4.0.0-dev.4

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
